version: 1.0.{build}
image: Visual Studio 2017
install:
  - dotnet tool install -g Cake.Tool --version 0.31.0 
build_script:
- cmd: dotnet cake -Target=Sonar
- cmd: dotnet cake -Target=CreateArtifact -Project=Serilog.Sinks.Sentry
test: off
cache:
  - '%USERPROFILE%\.sonar\cache'
  - '%USERPROFILE%\.nuget\packages -> **\*.csproj'
  - 'tools -> build.cake'
